insert into PH7_User(
  US_ID,
  US_Name,
  US_RegAlias,
  US_RegTime,
  US_Password,
  US_RequestAddress,
  US_Root_Teams_ID,
  US_Teams_ID,
  US_Position_ID
) select 
  US_ID,
  US_UserNumber,
  US_Name,
  sysdate, --US_RegTime
  '70925DE1792D534BD8E48510929B28D5', --US_Password：初始化口令都为NZ@20211004，升级后由员工自行更改
  nvl(US_LoginAddress, '*'),
  655066332286001, --US_Root_Teams_ID：公司8，导入后通过界面纠正
  655066332286002, --US_PT_ID：软件部，导入后通过界面纠正
  3 --US_Position_ID：项目经理，导入后通过界面纠正
from PH_User
where 
   US_Locked = 0 or
   US_ID <= 0


insert into PT7_PROJECT_INFO(
   PI_ID,
   PI_CONT_NUMBER,
   PI_CONT_APPROVE_DATE,
   PI_PROJECT_NAME,
   PI_PROJECT_TYPE_FG,
   PI_PROJECT_MANAGER,
   PI_DEVELOP_MANAGER,
   PI_MAINTENANCE_MANAGER,
   PI_SALES_MANAGER,
   PI_SALES_AREA,
   PI_CUSTOMER,
   PI_CONT_AMOUNT,
   PI_CONT_MARGIN,
   PI_PRODUCT_VERSION,
   PI_PRODUCT_PRICE,
   PI_MAINTENANCE_PRICE,
   PI_CONT_PAY_CLAUSE,
   PI_CONT_BREACH_CLAUSE,
   PI_CONT_SEALING_CLAUSE,
   PI_CONT_DEFENSIVE_CLAUSE,
   PI_CONT_DURATION_CLAUSE,
   PI_CONT_ACCEPTANCE_CLAUSE,
   PI_CONT_ACCEPTANCE_DOCS,
   PI_CONT_DOCS_PATH,
   PI_ONLINE_PLAN_DATE,
   PI_ONLINE_ACTUAL_DATE,
   PI_ACCEPT_DATE,
   PI_ESTIMATE_WORKLOAD,
   PI_MANAGE_WORK_FG,
   PI_INVESTIGATE_WORK_FG,
   PI_DEVELOP_WORK_FG,
   PI_TEST_WORK_FG,
   PI_IMPLEMENT_WORK_FG,
   PI_MAINTENANCE_WORK_FG,
   PI_ORIGINATOR,
   PI_ORIGINATE_TIME,
   PI_ORIGINATE_TEAMS,
   PI_UPDATER,
   PI_UPDATE_TIME,
   PI_CLOSED_DATE,
   PI_CURRENT_STATUS,
   PI_ANNUAL_MILESTONE
) select 
   PI_ID,
   nvl(PI_CONT_NUMBER, SEQ_PH.NEXTVAL),
   nvl(PI_CONT_APPROVE_DATE, sysdate),
   PI_PROJECT_NAME,
   PI_PROJECT_TYPE_FG,
   nvl((select US_ID from PH_User where PH_User.US_Name=PI_PROJECT_MANAGER), 0),
   nvl((select US_ID from PH_User where PH_User.US_Name=PI_DEVELOP_MANAGER), 0),
   nvl((select US_ID from PH_User where PH_User.US_Name=PI_PROJECT_SUPERVISOR), 0),
   nvl((select US_ID from PH_User where PH_User.US_Name=PI_SALES_MANAGER), 0),
   PI_CUSTOMER, --PI_SALES_AREA
   PI_CUSTOMER,
   PI_CONT_AMOUNT,
   PI_CONT_AMOUNT, --PI_CONT_MARGIN
   '*', --PI_PRODUCT_VERSION
   0, --PI_PRODUCT_PRICE
   0, --PI_MAINTENANCE_PRICE
   PI_CONT_PAY_CLAUSE,
   PI_CONT_BREACH_CLAUSE,
   PI_CONT_SEALING_CLAUSE,
   PI_CONT_DEFENSIVE_CLAUSE,
   PI_CONT_DURATION_CLAUSE,
   PI_CONT_ACCEPTANCE_CLAUSE,
   PI_CONT_ACCEPTANCE_DOCS,
   PI_CONT_DOCS_PATH,
   PI_ONLINE_PLAN_DATE,
   PI_ONLINE_ACTUAL_DATE,
   null, --PI_ACCEPT_DATE
   PI_ESTIMATE_WORKLOAD,
   PI_MANAGE_WORK_FG,
   PI_INVESTIGATE_WORK_FG,
   PI_DEVELOP_WORK_FG,
   PI_TEST_WORK_FG,
   PI_IMPLEMENT_WORK_FG,
   PI_MAINTENANCE_WORK_FG,
   PI_ORIGINATOR,
   PI_ORIGINATETIME,
   655066332286001, --PI_ORIGINATE_TEAMS：公司8
   PI_INPUTER,
   PI_INPUTTIME,
   PI_CLOSED_DATE,
   PI_CURRENT_STATUS,
   PI_ANNUAL_AIM
 --from (select ROW_NUMBER() OVER(PARTITION BY PI_CONT_NUMBER ORDER BY PI_ID DESC) rn,
 --  PI_ID,
 --  nvl(PI_CONT_NUMBER, SEQ_PH.NEXTVAL),
 --  nvl(PI_CONT_APPROVE_DATE, sysdate),
 --  PI_PROJECT_NAME,
 --  PI_PROJECT_TYPE_FG,
 --  PI_PROJECT_MANAGER,
 --  PI_DEVELOP_MANAGER,
 --  PI_PROJECT_SUPERVISOR,
 --  PI_SALES_MANAGER,
 --  PI_CUSTOMER,
 --  PI_CONT_AMOUNT,
 --  PI_CONT_PAY_CLAUSE,
 --  PI_CONT_BREACH_CLAUSE,
 --  PI_CONT_SEALING_CLAUSE,
 --  PI_CONT_DEFENSIVE_CLAUSE,
 --  PI_CONT_DURATION_CLAUSE,
 --  PI_CONT_ACCEPTANCE_CLAUSE,
 --  PI_CONT_ACCEPTANCE_DOCS,
 --  PI_CONT_DOCS_PATH,
 --  PI_ONLINE_PLAN_DATE,
 --  PI_ONLINE_ACTUAL_DATE,
 --  PI_ESTIMATE_WORKLOAD,
 --  PI_MANAGE_WORK_FG,
 --  PI_INVESTIGATE_WORK_FG,
 --  PI_DEVELOP_WORK_FG,
 --  PI_TEST_WORK_FG,
 --  PI_IMPLEMENT_WORK_FG,
 --  PI_MAINTENANCE_WORK_FG,
 --  PI_ORIGINATOR,
 --  PI_ORIGINATETIME,
 --  PI_INPUTER,
 --  PI_INPUTTIME,
 --  PI_CLOSED_DATE
from PT_PROJECT_INFO
where 
   PI_PROJECT_TYPE_FG = 0
--) WHERE rn = 1


insert into PT7_PROJECT_MONTHLY_REPORT(
   PM_ID,
   PM_PI_ID_WM,
   PM_YEAR_WM,
   PM_MONTH_WM,
   PM_STATUS,
   PM_MONTHLY_PLAN,
   PM_MONTHLY_ACHIEVE,
   PM_NEXT_MONTHLY_PLAN,
   PM_RISK_CAUTION,
   PM_DEMAND_COORDINATION,
   PM_ORIGINATOR,
   PM_ORIGINATE_TIME,
   PM_UPDATER,
   PM_UPDATE_TIME
) select 
   PR_ID,
   PR_PI_ID,
   PR_YEAR,
   PR_MONTH,
   '*', --PM_STATUS
   nvl(PR_MONTHLY_PLAN, '*'),
   nvl(PR_MONTHLY_ACHIEVE, '*'),
   nvl(PR_NEXT_PLAN, '*'),
   PR_RISK_CAUTION,
   PR_DEMAND_COORDINATION,
   nvl((select US_ID from PH_User where PH_User.US_UserNumber=PR_ORIGINATOR), 0),
   PR_ORIGINATETIME,
   nvl((select US_ID from PH_User where PH_User.US_UserNumber=PR_INPUTER), 0),
   PR_INPUTTIME
from PT_PROJECT_MONTHLY_REPORT